/****************************************************************************
 * Copyright (C) 2010
 * by Dimok
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any
 * damages arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any
 * purpose, including commercial applications, and to alter it and
 * redistribute it freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you
 * must not claim that you wrote the original software. If you use
 * this software in a product, an acknowledgment in the product
 * documentation would be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and
 * must not be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 * distribution.
 ***************************************************************************/
#include <ogcsys.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "CSettings.h"
#include "CGameSettings.h"
#include "FileOperations/fileops.h"
#include "svnrev.h"

#define VALID_CONFIG_REV	1031

CGameSettings GameSettings;

CGameSettings::CGameSettings()
{
	SetDefault(DefaultConfig);
}

CGameSettings::~CGameSettings()
{
}

GameCFG * CGameSettings::GetGameCFG(const char * id)
{
	if(!id)
	{
		DefaultConfig.id[0] = '\0';
		return &DefaultConfig;
	}

	const std::string key(id);
	if (GameMap.count(key)) {
		return GameMap[key].get();
	}

	memcpy(DefaultConfig.id, id, 6);

	return &DefaultConfig;
}

bool CGameSettings::AddGame(std::unique_ptr<GameCFG> NewGame)
{
	const std::string key(NewGame->id);
	GameMap[key] = std::move(NewGame);
	return true;
}

bool CGameSettings::RemoveAll()
{
	GameMap.clear();
	std::unordered_map<std::string, std::unique_ptr<GameCFG>>().swap(GameMap);

	return Save();
}

bool CGameSettings::Remove(const char * id)
{
	if(!id)
		return false;

	const std::string key(id);
	GameMap.erase(key);
	return true;
}

bool CGameSettings::Load(const char * path)
{
	char filepath[300];
	snprintf(filepath, sizeof(filepath), "%sGXGameSettings.cfg", path);

	ConfigPath = filepath;

	FILE *file = fopen(filepath, "r");
	if (!file) return false;

	if(!ValidVersion(file))
	{
		fclose(file);
		return false;
	}

	const int lineSize = 20*1024;

	char *line = new (std::nothrow) char[lineSize];
	if(!line) {
		fclose(file);
		return false;
	}

	while (fgets(line, lineSize, file))
	{
		if (line[0] == '#')
			continue;

		this->ParseLine(line);
	}

	delete [] line;

	fclose(file);

	return true;
}

bool CGameSettings::ValidVersion(FILE * file)
{
	if(!file) return false;

	char line[255];
	int revision = 0;

	while (fgets(line, sizeof(line), file))
	{
		const char * ptr = strcasestr(line, "USB Loader GX R");
		if(ptr)
		{
			ptr += strlen("USB Loader GX R");
			revision = atoi(ptr);
			break;
		}
	}

	rewind(file);

	return revision >= VALID_CONFIG_REV;
}

bool CGameSettings::Save()
{
	char filepath[300];
	strlcpy(filepath, ConfigPath.c_str(), sizeof(filepath));

	char * ptr = strrchr(filepath, '/');
	if(ptr)
		ptr[0] = 0;

	FILE * f = fopen(ConfigPath.c_str(), "w");
	if (!f) return false;

	fprintf(f, "# USB Loader GX R%s - Individual game settings file\n", GetRev());
	fprintf(f, "# note: this file is automatically generated\n");
	fprintf(f, "# Num Games: %d\n", GameMap.size());
	for (const auto& pair : GameMap)
	{
		GameCFG& game = *pair.second;

		fprintf(f, "game:%s = ", game.id);
		fprintf(f, "video:%d; ", game.video);
		fprintf(f, "videoPatchDol:%d; ", game.videoPatchDol);
		fprintf(f, "patchFix480p:%d; ", game.patchFix480p);
		fprintf(f, "deflicker:%d; ", game.deflicker);
		fprintf(f, "videowidth:%d; ", game.videoWidth);
		fprintf(f, "aspectratio:%d; ", game.aspectratio);
		fprintf(f, "language:%d; ", game.language);
		fprintf(f, "ocarina:%d; ", game.ocarina);
		fprintf(f, "vipatch:%d; ", game.vipatch);
		fprintf(f, "ios:%d; ", game.ios);
		fprintf(f, "autoios:%d; ", game.autoios);
		fprintf(f, "parentalcontrol:%d; ", game.parentalcontrol);
		fprintf(f, "iosreloadblock:%d; ", game.iosreloadblock);
		fprintf(f, "patchcountrystrings:%d; ", game.patchcountrystrings);
		fprintf(f, "loadalternatedol:%d; ", game.loadalternatedol);
		fprintf(f, "alternatedolstart:%d; ", (int)game.alternatedolstart);
		fprintf(f, "alternatedolname:%s; ", game.alternatedolname.c_str());
		fprintf(f, "returnTo:%d; ", game.returnTo);
		fprintf(f, "sneekVideoPatch:%d; ", game.sneekVideoPatch);
		fprintf(f, "NandEmuMode:%d; ", game.NandEmuMode);
		fprintf(f, "NandEmuPath:%s; ", game.NandEmuPath.c_str());
		fprintf(f, "Hooktype:%d; ", game.Hooktype);
		fprintf(f, "WiirdDebugger:%d; ", game.WiirdDebugger);
		fprintf(f, "GameCubeMode:%d; ", game.GameCubeMode);
		fprintf(f, "DMLVideo:%d; ", game.DMLVideo);
		fprintf(f, "DMLProgPatch:%d; ", game.DMLProgPatch);
		fprintf(f, "DMLNMM:%d; ", game.DMLNMM);
		fprintf(f, "DMLActivityLED:%d; ", game.DMLActivityLED);
		fprintf(f, "DMLPADHOOK:%d; ", game.DMLPADHOOK);
		fprintf(f, "DMLNoDisc2:%d; ", game.DMLNoDisc2);
		fprintf(f, "DMLWidescreen:%d; ", game.DMLWidescreen);
		fprintf(f, "DMLScreenshot:%d; ", game.DMLScreenshot);
		fprintf(f, "DMLJPNPatch:%d; ", game.DMLJPNPatch);
		fprintf(f, "DMLDebug:%d; ", game.DMLDebug);
		fprintf(f, "NINDeflicker:%d; ", game.NINDeflicker);
		fprintf(f, "NINPal50Patch:%d; ", game.NINPal50Patch);
		fprintf(f, "NINWiiUWide:%d; ", game.NINWiiUWide);
		fprintf(f, "NINVideoScale:%d; ", game.NINVideoScale);
		fprintf(f, "NINVideoOffset:%d; ", game.NINVideoOffset);
		fprintf(f, "NINRemlimit:%d; ", game.NINRemlimit);
		fprintf(f, "NINArcadeMode:%d; ", game.NINArcadeMode);
		fprintf(f, "NINCCRumble:%d; ", game.NINCCRumble);
		fprintf(f, "NINSkipIPL:%d; ", game.NINSkipIPL);
		fprintf(f, "NINBBA:%d; ", game.NINBBA);
		fprintf(f, "NINBBAProfile:%d; ", game.NINBBAProfile);
		fprintf(f, "NINMCEmulation:%d; ", game.NINMCEmulation);
		fprintf(f, "NINMCSize:%d; ", game.NINMCSize);
		fprintf(f, "NINUSBHID:%d; ", game.NINUSBHID);
		fprintf(f, "NINMaxPads:%d; ", game.NINMaxPads);
		fprintf(f, "NINNativeSI:%d; ", game.NINNativeSI);
		fprintf(f, "NINOSReport:%d; ", game.NINOSReport);
		fprintf(f, "NINLED:%d; ", game.NINLED);
		fprintf(f, "NINLog:%d; ", game.NINLog);
		fprintf(f, "NINLoaderPath:%s; ", game.NINLoaderPath.c_str());
		fprintf(f, "DEVOMCEmulation:%d; ", game.DEVOMCEmulation);
		fprintf(f, "DEVOWidescreen:%d; ", game.DEVOWidescreen);
		fprintf(f, "DEVOActivityLED:%d; ", game.DEVOActivityLED);
		fprintf(f, "DEVOFZeroAX:%d; ", game.DEVOFZeroAX);
		fprintf(f, "DEVOTimerFix:%d; ", game.DEVOTimerFix);
		fprintf(f, "DEVODButtons:%d; ", game.DEVODButtons);
		fprintf(f, "DEVOCropOverscan:%d; ", game.DEVOCropOverscan);
		fprintf(f, "DEVODiscDelay:%d; ", game.DEVODiscDelay);
		fprintf(f, "PrivateServer:%d; ", game.PrivateServer);
		fprintf(f, "CustomAddress:%s; ", game.CustomAddress.c_str());
		fprintf(f, "Locked:%d;\n", game.Locked);
	}
	fprintf(f, "# END\n");
	fclose(f);

	return true;
}

bool CGameSettings::SetSetting(GameCFG & game, const char *name, const char *value)
{
	short *target;

	if (strcmp(name, "video") == 0)
	{
		target = &game.video;
		goto handle_short;
	}
	else if (strcmp(name, "videoPatchDol") == 0)
	{
		target = &game.videoPatchDol;
		goto handle_short;
	}
	else if (strcmp(name, "patchFix480p") == 0)
	{
		target = &game.patchFix480p;
		goto handle_short;
	}
	else if (strcmp(name, "deflicker") == 0)
	{
		target = &game.deflicker;
		goto handle_short;
	}
	else if(strcmp(name, "videowidth") == 0)
	{
		target = &game.videoWidth;
		goto handle_short;
	}
	else if(strcmp(name, "aspectratio") == 0)
	{
		target = &game.aspectratio;
		goto handle_short;
	}
	else if(strcmp(name, "language") == 0)
	{
		target = &game.language;
		goto handle_short;
	}
	else if(strcmp(name, "ocarina") == 0)
	{
		target = &game.ocarina;
		goto handle_short;
	}
	else if(strcmp(name, "vipatch") == 0)
	{
		target = &game.vipatch;
		goto handle_short;
	}
	else if(strcmp(name, "ios") == 0)
	{
		target = &game.ios;
		goto handle_short;
	}
	else if(strcmp(name, "autoios") == 0)
	{
		target = &game.autoios;
		goto handle_short;
	}
	else if(strcmp(name, "parentalcontrol") == 0)
	{
		target = &game.parentalcontrol;
		goto handle_short;
	}
	else if(strcmp(name, "iosreloadblock") == 0)
	{
		target = &game.iosreloadblock;
		goto handle_short;
	}
	else if(strcmp(name, "loadalternatedol") == 0)
	{
		target = &game.loadalternatedol;
		goto handle_short;
	}
	else if(strcmp(name, "alternatedolstart") == 0)
	{
		game.alternatedolstart = atoi(value);
		return true;
	}
	else if(strcmp(name, "patchcountrystrings") == 0)
	{
		target = &game.patchcountrystrings;
		goto handle_short;
	}
	else if(strcmp(name, "alternatedolname") == 0)
	{
		game.alternatedolname = value;
		return true;
	}
	else if(strcmp(name, "returnTo") == 0)
	{
		target = &game.returnTo;
		goto handle_short;
	}
	else if(strcmp(name, "sneekVideoPatch") == 0)
	{
		target = &game.sneekVideoPatch;
		goto handle_short;
	}
	else if(strcmp(name, "NandEmuMode") == 0)
	{
		target = &game.NandEmuMode;
		goto handle_short;
	}
	else if(strcmp(name, "NandEmuPath") == 0)
	{
		game.NandEmuPath = value;
		return true;
	}
	else if(strcmp(name, "Hooktype") == 0)
	{
		target = &game.Hooktype;
		goto handle_short;
	}
	else if(strcmp(name, "WiirdDebugger") == 0)
	{
		target = &game.WiirdDebugger;
		goto handle_short;
	}
	else if(strcmp(name, "Locked") == 0)
	{
		target = &game.Locked;
		goto handle_short;
	}
	else if(strcmp(name, "GameCubeMode") == 0)
	{
		target = &game.GameCubeMode;
		goto handle_short;
	}
	else if(strcmp(name, "DMLVideo") == 0)
	{
		target = &game.DMLVideo;
		goto handle_short;
	}
	else if(strcmp(name, "DMLProgPatch") == 0)
	{
		target = &game.DMLProgPatch;
		goto handle_short;
	}
	else if(strcmp(name, "DMLNMM") == 0)
	{
		target = &game.DMLNMM;
		goto handle_short;
	}
	else if(strcmp(name, "DMLActivityLED") == 0)
	{
		target = &game.DMLActivityLED;
		goto handle_short;
	}
	else if(strcmp(name, "DMLPADHOOK") == 0)
	{
		target = &game.DMLPADHOOK;
		goto handle_short;
	}
	else if(strcmp(name, "DMLNoDisc2") == 0)
	{
		target = &game.DMLNoDisc2;
		goto handle_short;
	}
	else if(strcmp(name, "DMLWidescreen") == 0)
	{
		target = &game.DMLWidescreen;
		goto handle_short;
	}
	else if(strcmp(name, "DMLScreenshot") == 0)
	{
		target = &game.DMLScreenshot;
		goto handle_short;
	}
	else if(strcmp(name, "DMLJPNPatch") == 0)
	{
		target = &game.DMLJPNPatch;
		goto handle_short;
	}
	else if(strcmp(name, "DMLDebug") == 0)
	{
		target = &game.DMLDebug;
		goto handle_short;
	}
	else if(strcmp(name, "NINDeflicker") == 0)
	{
		target = &game.NINDeflicker;
		goto handle_short;
	}
	else if(strcmp(name, "NINPal50Patch") == 0)
	{
		target = &game.NINPal50Patch;
		goto handle_short;
	}
	else if(strcmp(name, "NINWiiUWide") == 0)
	{
		target = &game.NINWiiUWide;
		goto handle_short;
	}
	else if (strcmp(name, "NINVideoScale") == 0)
	{
		target = &game.NINVideoScale;
		goto handle_short;
	}
	else if (strcmp(name, "NINVideoOffset") == 0)
	{
		target = &game.NINVideoOffset;
		goto handle_short;
	}
	else if (strcmp(name, "NINRemlimit") == 0)
	{
		target = &game.NINRemlimit;
		goto handle_short;
	}
	else if(strcmp(name, "NINArcadeMode") == 0)
	{
		target = &game.NINArcadeMode;
		goto handle_short;
	}
	else if (strcmp(name, "NINCCRumble") == 0)
	{
		target = &game.NINCCRumble;
		goto handle_short;
	}
	else if (strcmp(name, "NINSkipIPL") == 0)
	{
		target = &game.NINSkipIPL;
		goto handle_short;
	}
	else if (strcmp(name, "NINBBA") == 0)
	{
		target = &game.NINBBA;
		goto handle_short;
	}
	else if (strcmp(name, "NINBBAProfile") == 0)
	{
		target = &game.NINBBAProfile;
		goto handle_short;
	}
	else if(strcmp(name, "NINMCEmulation") == 0)
	{
		target = &game.NINMCEmulation;
		goto handle_short;
	}
	else if(strcmp(name, "NINMCSize") == 0)
	{
		target = &game.NINMCSize;
		goto handle_short;
	}
	else if(strcmp(name, "NINUSBHID") == 0)
	{
		target = &game.NINUSBHID;
		goto handle_short;
	}
	else if(strcmp(name, "NINMaxPads") == 0)
	{
		target = &game.NINMaxPads;
		goto handle_short;
	}
	else if(strcmp(name, "NINNativeSI") == 0)
	{
		target = &game.NINNativeSI;
		goto handle_short;
	}
	else if(strcmp(name, "NINOSReport") == 0)
	{
		target = &game.NINOSReport;
		goto handle_short;
	}
	else if(strcmp(name, "NINLED") == 0)
	{
		target = &game.NINLED;
		goto handle_short;
	}
	else if(strcmp(name, "NINLog") == 0)
	{
		target = &game.NINLog;
		goto handle_short;
	}
	else if(strcmp(name, "NINLoaderPath") == 0)
	{
		game.NINLoaderPath = value;
		return true;
	}
	else if(strcmp(name, "DEVOMCEmulation") == 0)
	{
		target = &game.DEVOMCEmulation;
		goto handle_short;
	}
	else if(strcmp(name, "DEVOWidescreen") == 0)
	{
		target = &game.DEVOWidescreen;
		goto handle_short;
	}
	else if(strcmp(name, "DEVOActivityLED") == 0)
	{
		target = &game.DEVOActivityLED;
		goto handle_short;
	}
	else if(strcmp(name, "DEVOFZeroAX") == 0)
	{
		target = &game.DEVOFZeroAX;
		goto handle_short;
	}
	else if(strcmp(name, "DEVOTimerFix") == 0)
	{
		target = &game.DEVOTimerFix;
		goto handle_short;
	}
	else if(strcmp(name, "DEVODButtons") == 0)
	{
		target = &game.DEVODButtons;
		goto handle_short;
	}
	else if(strcmp(name, "DEVOCropOverscan") == 0)
	{
		target = &game.DEVOCropOverscan;
		goto handle_short;
	}
	else if(strcmp(name, "DEVODiscDelay") == 0)
	{
		target = &game.DEVODiscDelay;
		goto handle_short;
	}
	else if(strcmp(name, "PrivateServer") == 0)
	{
		target = &game.PrivateServer;
		goto handle_short;
	}
	else if(strcmp(name, "CustomAddress") == 0)
	{
		if(strlen(value) > 3)
			game.CustomAddress = value;
		return true;
	}

	return false;

handle_short:
	*target = atoi(value);
	return true;
}

bool CGameSettings::ReadGameID(const char * src, char * GameID, int size)
{
	if(strncasecmp(src, "game:", 5) != 0)
		return false;

	char * ptr = strchr(src, ':');
	if(!ptr)
		return false;

	ptr++;

	int i = 0;

	for(i = 0; i < size; i++, ptr++)
	{
		if(*ptr == ' ' || *ptr == '\0')
			break;

		GameID[i] = *ptr;
	}

	GameID[i] = 0;

	return true;
}

void CGameSettings::ParseLine(char *line)
{
	char GameID[8];

	if(!ReadGameID(line, GameID, 6))
		return;

	if(strlen(GameID) != 6 && strlen(GameID) != 4)
		return;

	std::unique_ptr<GameCFG> NewCFG = std::make_unique<GameCFG>();
	SetDefault(*NewCFG);

	strcpy(NewCFG->id, GameID);

	char * LinePtr = strchr(line, '=');

	while(LinePtr != NULL)
	{
		LinePtr++;

		char * eq = strchr(LinePtr, ':');

		if (!eq) break;

		std::string name, value;

		this->TrimLine(name, LinePtr, ':');
		this->TrimLine(value, eq + 1, ';');

		SetSetting(*NewCFG, name.c_str(), value.c_str());

		LinePtr = strchr(LinePtr, ';');
	}

	AddGame(std::move(NewCFG));
}

void CGameSettings::TrimLine(std::string &dest, const char *src, char stopChar)
{
	if(!src)
		return;

	while (*src == ' ')
		src++;

	while(*src != 0)
	{
		if(*src == stopChar || *src == '\n' || *src == '\r')
			break;

		dest.push_back(*src);
		src++;
	}
}

int CGameSettings::GetPartenalPEGI(int parental)
{
	switch(parental)
	{
		case 1: return 7;
		case 2: return 12;
		case 3: return 16;
		case 4: return 18;
		default: return -1;
	}
}

void CGameSettings::SetDefault(GameCFG &game)
{
	memset(game.id, 0, sizeof(game.id));
	game.video = INHERIT;
	game.videoPatchDol = INHERIT;
	game.patchFix480p = INHERIT;
	game.deflicker = INHERIT;
	game.videoWidth = INHERIT;
	game.aspectratio = INHERIT;
	game.language = INHERIT;
	game.ocarina = INHERIT;
	game.vipatch = INHERIT;
	game.ios = INHERIT;
	game.autoios = INHERIT;
	game.parentalcontrol = PARENTAL_LVL_EVERYONE;
	game.patchcountrystrings = INHERIT;
	game.loadalternatedol = ALT_DOL_DEFAULT;
	game.alternatedolstart = 0;
	game.iosreloadblock = INHERIT;
	game.alternatedolname.clear();
	game.returnTo = ON;
	game.sneekVideoPatch = INHERIT;
	game.NandEmuMode = INHERIT;
	game.NandEmuPath.clear();
	game.Hooktype = INHERIT;
	game.WiirdDebugger = INHERIT;
	game.GameCubeMode = INHERIT;
	game.DMLVideo = INHERIT;
	game.DMLProgPatch = INHERIT;
	game.DMLNMM = INHERIT;
	game.DMLActivityLED = INHERIT;
	game.DMLPADHOOK = INHERIT;
	game.DMLNoDisc2 = INHERIT;
	game.DMLWidescreen = INHERIT;
	game.DMLScreenshot = INHERIT;
	game.DMLJPNPatch = INHERIT;
	game.DMLDebug = INHERIT;
	game.NINDeflicker = INHERIT;
	game.NINPal50Patch = INHERIT;
	game.NINWiiUWide = INHERIT;
	game.NINVideoScale = INHERIT;
	game.NINVideoOffset = INHERIT - 20;
	game.NINRemlimit = INHERIT;
	game.NINArcadeMode = INHERIT;
	game.NINCCRumble = INHERIT;
	game.NINSkipIPL = INHERIT;
	game.NINBBA = INHERIT;
	game.NINBBAProfile = INHERIT;
	game.NINMCEmulation = INHERIT;
	game.NINMCSize = INHERIT;
	game.NINUSBHID = INHERIT;
	game.NINMaxPads = INHERIT;
	game.NINNativeSI = INHERIT;
	game.NINOSReport = INHERIT;
	game.NINLED = INHERIT;
	game.NINLog = INHERIT;
	game.NINLoaderPath.clear();
	game.DEVOMCEmulation = INHERIT;
	game.DEVOWidescreen = INHERIT;
	game.DEVOActivityLED = INHERIT;
	game.DEVOFZeroAX = INHERIT;
	game.DEVOTimerFix = INHERIT;
	game.DEVODButtons = INHERIT;
	game.DEVOCropOverscan = INHERIT;
	game.DEVODiscDelay = INHERIT;
	game.PrivateServer = INHERIT;
	game.CustomAddress.clear();
	game.Locked = OFF;
}
