/****************************************************************************
 * Copyright (C) 2010
 * by Dimok
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any
 * damages arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any
 * purpose, including commercial applications, and to alter it and
 * redistribute it freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you
 * must not claim that you wrote the original software. If you use
 * this software in a product, an acknowledgment in the product
 * documentation would be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and
 * must not be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 * distribution.
 ***************************************************************************/
#include <ogcsys.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "CSettings.h"
#include "CGameSettings.h"
#include "FileOperations/fileops.h"
#include "svnrev.h"

#define VALID_CONFIG_REV	1031

CGameSettings GameSettings;

CGameSettings::CGameSettings()
{
	SetDefault(DefaultConfig);
}

CGameSettings::~CGameSettings()
{
}

GameCFG * CGameSettings::GetGameCFG(const char * id)
{
	if(!id)
	{
		DefaultConfig.id[0] = '\0';
		return &DefaultConfig;
	}

	const std::string key(id);
	if (GameMap.count(key)) {
		return GameMap[key].get();
	}

	memcpy(DefaultConfig.id, id, 6);

	return &DefaultConfig;
}

bool CGameSettings::AddGame(std::unique_ptr<GameCFG> NewGame)
{
	const std::string key(NewGame->id);
	GameMap[key] = std::move(NewGame);
	return true;
}

bool CGameSettings::RemoveAll()
{
	GameMap.clear();
	std::unordered_map<std::string, std::unique_ptr<GameCFG>>().swap(GameMap);

	return Save();
}

bool CGameSettings::Remove(const char * id)
{
	if(!id)
		return false;

	const std::string key(id);
	GameMap.erase(key);
	return true;
}

bool CGameSettings::Load(const char * path)
{
	char filepath[300];
	snprintf(filepath, sizeof(filepath), "%sGXGameSettings.cfg", path);

	ConfigPath = filepath;

	FILE *file = fopen(filepath, "r");
	if (!file) return false;

	if(!ValidVersion(file))
	{
		fclose(file);
		return false;
	}

	const int lineSize = 20*1024;

	char *line = new (std::nothrow) char[lineSize];
	if(!line) {
		fclose(file);
		return false;
	}

	while (fgets(line, lineSize, file))
	{
		if (line[0] == '#')
			continue;

		this->ParseLine(line);
	}

	delete [] line;

	fclose(file);

	return true;
}

bool CGameSettings::ValidVersion(FILE * file)
{
	if(!file) return false;

	char line[255];
	int revision = 0;

	while (fgets(line, sizeof(line), file))
	{
		const char * ptr = strcasestr(line, "USB Loader GX R");
		if(ptr)
		{
			ptr += strlen("USB Loader GX R");
			revision = atoi(ptr);
			break;
		}
	}

	rewind(file);

	return revision >= VALID_CONFIG_REV;
}

bool CGameSettings::Save()
{
	char filepath[300];
	strlcpy(filepath, ConfigPath.c_str(), sizeof(filepath));

	char * ptr = strrchr(filepath, '/');
	if(ptr)
		ptr[0] = 0;

	FILE * f = fopen(ConfigPath.c_str(), "w");
	if (!f) return false;

	fprintf(f, "# USB Loader GX R%s - Individual game settings file\n", GetRev());
	fprintf(f, "# note: this file is automatically generated\n");
	fprintf(f, "# Num Games: %d\n", GameMap.size());
	for (const auto& pair : GameMap)
	{
		GameCFG& game = *pair.second;

		fprintf(f, "game:%s = ", game.id);
		fprintf(f, "video:%d; ", game.video);
		fprintf(f, "videoPatchDol:%d; ", game.videoPatchDol);
		fprintf(f, "patchFix480p:%d; ", game.patchFix480p);
		fprintf(f, "deflicker:%d; ", game.deflicker);
		fprintf(f, "videowidth:%d; ", game.videoWidth);
		fprintf(f, "aspectratio:%d; ", game.aspectratio);
		fprintf(f, "language:%d; ", game.language);
		fprintf(f, "ocarina:%d; ", game.ocarina);
		fprintf(f, "vipatch:%d; ", game.vipatch);
		fprintf(f, "ios:%d; ", game.ios);
		fprintf(f, "autoios:%d; ", game.autoios);
		fprintf(f, "parentalcontrol:%d; ", game.parentalcontrol);
		fprintf(f, "iosreloadblock:%d; ", game.iosreloadblock);
		fprintf(f, "patchcountrystrings:%d; ", game.patchcountrystrings);
		fprintf(f, "loadalternatedol:%d; ", game.loadalternatedol);
		fprintf(f, "alternatedolstart:%d; ", (int)game.alternatedolstart);
		fprintf(f, "alternatedolname:%s; ", game.alternatedolname.c_str());
		fprintf(f, "returnTo:%d; ", game.returnTo);
		fprintf(f, "sneekVideoPatch:%d; ", game.sneekVideoPatch);
		fprintf(f, "NandEmuMode:%d; ", game.NandEmuMode);
		fprintf(f, "NandEmuPath:%s; ", game.NandEmuPath.c_str());
		fprintf(f, "Hooktype:%d; ", game.Hooktype);
		fprintf(f, "WiirdDebugger:%d; ", game.WiirdDebugger);
		fprintf(f, "GameCubeMode:%d; ", game.GameCubeMode);
		fprintf(f, "DMLVideo:%d; ", game.DMLVideo);
		fprintf(f, "DMLProgPatch:%d; ", game.DMLProgPatch);
		fprintf(f, "DMLNMM:%d; ", game.DMLNMM);
		fprintf(f, "DMLActivityLED:%d; ", game.DMLActivityLED);
		fprintf(f, "DMLPADHOOK:%d; ", game.DMLPADHOOK);
		fprintf(f, "DMLNoDisc2:%d; ", game.DMLNoDisc2);
		fprintf(f, "DMLWidescreen:%d; ", game.DMLWidescreen);
		fprintf(f, "DMLScreenshot:%d; ", game.DMLScreenshot);
		fprintf(f, "DMLJPNPatch:%d; ", game.DMLJPNPatch);
		fprintf(f, "DMLDebug:%d; ", game.DMLDebug);
		fprintf(f, "NINDeflicker:%d; ", game.NINDeflicker);
		fprintf(f, "NINPal50Patch:%d; ", game.NINPal50Patch);
		fprintf(f, "NINWiiUWide:%d; ", game.NINWiiUWide);
		fprintf(f, "NINVideoScale:%d; ", game.NINVideoScale);
		fprintf(f, "NINVideoOffset:%d; ", game.NINVideoOffset);
		fprintf(f, "NINRemlimit:%d; ", game.NINRemlimit);
		fprintf(f, "NINArcadeMode:%d; ", game.NINArcadeMode);
		fprintf(f, "NINCCRumble:%d; ", game.NINCCRumble);
		fprintf(f, "NINSkipIPL:%d; ", game.NINSkipIPL);
		fprintf(f, "NINBBA:%d; ", game.NINBBA);
		fprintf(f, "NINBBAProfile:%d; ", game.NINBBAProfile);
		fprintf(f, "NINMCEmulation:%d; ", game.NINMCEmulation);
		fprintf(f, "NINMCSize:%d; ", game.NINMCSize);
		fprintf(f, "NINUSBHID:%d; ", game.NINUSBHID);
		fprintf(f, "NINMaxPads:%d; ", game.NINMaxPads);
		fprintf(f, "NINNativeSI:%d; ", game.NINNativeSI);
		fprintf(f, "NINOSReport:%d; ", game.NINOSReport);
		fprintf(f, "NINLED:%d; ", game.NINLED);
		fprintf(f, "NINLog:%d; ", game.NINLog);
		fprintf(f, "NINLoaderPath:%s; ", game.NINLoaderPath.c_str());
		fprintf(f, "DEVOMCEmulation:%d; ", game.DEVOMCEmulation);
		fprintf(f, "DEVOWidescreen:%d; ", game.DEVOWidescreen);
		fprintf(f, "DEVOActivityLED:%d; ", game.DEVOActivityLED);
		fprintf(f, "DEVOFZeroAX:%d; ", game.DEVOFZeroAX);
		fprintf(f, "DEVOTimerFix:%d; ", game.DEVOTimerFix);
		fprintf(f, "DEVODButtons:%d; ", game.DEVODButtons);
		fprintf(f, "DEVOCropOverscan:%d; ", game.DEVOCropOverscan);
		fprintf(f, "DEVODiscDelay:%d; ", game.DEVODiscDelay);
		fprintf(f, "PrivateServer:%d; ", game.PrivateServer);
		fprintf(f, "CustomAddress:%s; ", game.CustomAddress.c_str());
		fprintf(f, "Locked:%d;\n", game.Locked);
	}
	fprintf(f, "# END\n");
	fclose(f);

	return true;
}

bool CGameSettings::SetSetting(GameCFG & game, const char *name, const char *value)
{
	short *target;

	switch (*name++) {
		case 'C':
			if(strcmp(name, "ustomAddress") == 0)
			{
				if(strlen(value) > 3)
					game.CustomAddress = value;
				return true;
			}

			break;

		case 'D':
			if (strcmp(name, "EVO") == 0)
			{
				name += 3;

				if(strcmp(name, "ActivityLED") == 0) target = &game.DEVOActivityLED;
				else if(strcmp(name, "CropOverscan") == 0) target = &game.DEVOCropOverscan;
				else if(strcmp(name, "DButtons") == 0) target = &game.DEVODButtons;
				else if(strcmp(name, "DiscDelay") == 0) target = &game.DEVODiscDelay;
				else if(strcmp(name, "FZeroAX") == 0) target = &game.DEVOFZeroAX;
				else if(strcmp(name, "MCEmulation") == 0) target = &game.DEVOMCEmulation;
				else if(strcmp(name, "TimerFix") == 0) target = &game.DEVOTimerFix;
				else if(strcmp(name, "Widescreen") == 0) target = &game.DEVOWidescreen;
				else break;

				goto handle_short;
			}
			else if (strcmp(name, "ML") == 0)
			{
				name += 2;

				if(strcmp(name, "ActivityLED") == 0) target = &game.DMLActivityLED;
				else if(strcmp(name, "Debug") == 0) target = &game.DMLDebug;
				else if(strcmp(name, "JPNPatch") == 0) target = &game.DMLJPNPatch;
				else if(strcmp(name, "NMM") == 0) target = &game.DMLNMM;
				else if(strcmp(name, "NoDisc2") == 0) target = &game.DMLNoDisc2;
				else if(strcmp(name, "PADHOOK") == 0) target = &game.DMLPADHOOK;
				else if(strcmp(name, "ProgPatch") == 0) target = &game.DMLProgPatch;
				else if(strcmp(name, "Screenshot") == 0) target = &game.DMLScreenshot;
				else if(strcmp(name, "Video") == 0) target = &game.DMLVideo;
				else if(strcmp(name, "Widescreen") == 0) target = &game.DMLWidescreen;
				else return false;

				goto handle_short;
			}

			break;

		case 'G':
			if(strcmp(name, "ameCubeMode") == 0)
			{
				target = &game.GameCubeMode;
				goto handle_short;
			}

			break;

		case 'H':
			if(strcmp(name, "ooktype") == 0)
			{
				target = &game.Hooktype;
				goto handle_short;
			}

			break;

		case 'L':
			if(strcmp(name, "ocked") == 0)
			{
				target = &game.Locked;
				goto handle_short;
			}

			break;

		case 'N':
			switch (*name++) {
				case 'a':
					if(strcmp(name, "ndEmuMode") == 0)
					{
						target = &game.NandEmuMode;
						goto handle_short;
					}
					else if(strcmp(name, "ndEmuPath") == 0)
					{
						game.NandEmuPath = value;
						return true;
					}

					break;
				case 'I':
					if (*name++ != 'N') break;
					else if(strcmp(name, "ArcadeMode") == 0) target = &game.NINArcadeMode;
					else if(strcmp(name, "BBA") == 0) target = &game.NINBBA;
					else if(strcmp(name, "BBAProfile") == 0) target = &game.NINBBAProfile;
					else if(strcmp(name, "CCRumble") == 0) target = &game.NINCCRumble;
					else if(strcmp(name, "Deflicker") == 0) target = &game.NINDeflicker;
					else if(strcmp(name, "LED") == 0) target = &game.NINLED;
					else if(strcmp(name, "Log") == 0) target = &game.NINLog;
					else if(strcmp(name, "MCEmulation") == 0) target = &game.NINMCEmulation;
					else if(strcmp(name, "MCSize") == 0) target = &game.NINMCSize;
					else if(strcmp(name, "MaxPads") == 0) target = &game.NINMaxPads;
					else if(strcmp(name, "NativeSI") == 0) target = &game.NINNativeSI;
					else if(strcmp(name, "OSReport") == 0) target = &game.NINOSReport;
					else if(strcmp(name, "Pal50Patch") == 0) target = &game.NINPal50Patch;
					else if(strcmp(name, "Remlimit") == 0) target = &game.NINRemlimit;
					else if(strcmp(name, "SkipIPL") == 0) target = &game.NINSkipIPL;
					else if(strcmp(name, "USBHID") == 0) target = &game.NINUSBHID;
					else if(strcmp(name, "VideoOffset") == 0) target = &game.NINVideoOffset;
					else if(strcmp(name, "VideoScale") == 0) target = &game.NINVideoScale;
					else if(strcmp(name, "WiiUWide") == 0) target = &game.NINWiiUWide;
					else if(strcmp(name, "LoaderPath") == 0)
					{
						game.NINLoaderPath = value;
						return true;
					}
					else break;

					goto handle_short;
			}

			break;

		case 'P':
			if(strcmp(name, "rivateServer") == 0)
			{
				target = &game.PrivateServer;
				goto handle_short;
			}

			break;

		case 'W':
			if(strcmp(name, "iirdDebugger") == 0)
			{
				target = &game.WiirdDebugger;
				goto handle_short;
			}

			break;

		case 'a':
			if(strcmp(name, "lternatedolname") == 0)
			{
				game.alternatedolname = value;
				return true;
			}
			else if(strcmp(name, "lternatedolstart") == 0)
			{
				game.alternatedolstart = atoi(value);
				return true;
			}
			else if(strcmp(name, "spectratio") == 0) target = &game.aspectratio;
			else if(strcmp(name, "utoios") == 0) target = &game.autoios;
			else break;

			goto handle_short;

		case 'd':
			if(strcmp(name, "eflicker") == 0)
			{
				target = &game.deflicker;
				goto handle_short;
			}

			break;

		case 'i':
			if(strcmp(name, "os") == 0) target = &game.ios;
			else if(strcmp(name, "osreloadblock") == 0) target = &game.iosreloadblock;
			else break;

			goto handle_short;

		case 'l':
			if(strcmp(name, "anguage") == 0) target = &game.language;
			else if(strcmp(name, "oadalternatedol") == 0) target = &game.loadalternatedol;
			else break;

			goto handle_short;

		case 'o':
			if(strcmp(name, "carina") == 0)
			{
				target = &game.ocarina;
				goto handle_short;
			}

			break;

		case 'p':
			if(strcmp(name, "arentalcontrol") == 0) target = &game.parentalcontrol;
			else if(strcmp(name, "atchFix480p") == 0) target = &game.patchFix480p;
			else if(strcmp(name, "atchcountrystrings") == 0) target = &game.patchcountrystrings;
			else break;

			goto handle_short;

		case 'r':
			if(strcmp(name, "eturnTo") == 0) {
				target = &game.returnTo;
				goto handle_short;
			}

			break;

		case 's':
			if(strcmp(name, "neekVideoPatch") == 0) {
				target = &game.sneekVideoPatch;
				goto handle_short;
			}

		case 'v':
			if(strcmp(name, "ideo") == 0)
			{
				if (!*(name += 4)) target = &game.video;
				else if(strcmp(name, "PatchDol") == 0) target = &game.videoPatchDol;
				else if(strcmp(name, "width") == 0) target = &game.videoWidth;
				else break;

				goto handle_short;
			}
			else if(strcmp(name, "ipatch") == 0)
			{
				target = &game.vipatch;
				goto handle_short;
			}

			break;
	}

	return false;

handle_short:
	*target = atoi(value);
	return true;
}

bool CGameSettings::ReadGameID(const char * src, char * GameID, int size)
{
	if(strncasecmp(src, "game:", 5) != 0)
		return false;

	char * ptr = strchr(src, ':');
	if(!ptr)
		return false;

	ptr++;

	int i = 0;

	for(i = 0; i < size; i++, ptr++)
	{
		if(*ptr == ' ' || *ptr == '\0')
			break;

		GameID[i] = *ptr;
	}

	GameID[i] = 0;

	return true;
}

void CGameSettings::ParseLine(char *line)
{
	char GameID[8];

	if(!ReadGameID(line, GameID, 6))
		return;

	if(strlen(GameID) != 6 && strlen(GameID) != 4)
		return;

	std::unique_ptr<GameCFG> NewCFG = std::make_unique<GameCFG>();
	SetDefault(*NewCFG);

	strcpy(NewCFG->id, GameID);

	char * LinePtr = strchr(line, '=');

	while(LinePtr != NULL)
	{
		LinePtr++;

		char * eq = strchr(LinePtr, ':');

		if (!eq) break;

		std::string name, value;

		this->TrimLine(name, LinePtr, ':');
		this->TrimLine(value, eq + 1, ';');

		SetSetting(*NewCFG, name.c_str(), value.c_str());

		LinePtr = strchr(LinePtr, ';');
	}

	AddGame(std::move(NewCFG));
}

void CGameSettings::TrimLine(std::string &dest, const char *src, char stopChar)
{
	if(!src)
		return;

	while (*src == ' ')
		src++;

	while(*src != 0)
	{
		if(*src == stopChar || *src == '\n' || *src == '\r')
			break;

		dest.push_back(*src);
		src++;
	}
}

int CGameSettings::GetPartenalPEGI(int parental)
{
	switch(parental)
	{
		case 1: return 7;
		case 2: return 12;
		case 3: return 16;
		case 4: return 18;
		default: return -1;
	}
}

void CGameSettings::SetDefault(GameCFG &game)
{
	memset(game.id, 0, sizeof(game.id));
	game.video = INHERIT;
	game.videoPatchDol = INHERIT;
	game.patchFix480p = INHERIT;
	game.deflicker = INHERIT;
	game.videoWidth = INHERIT;
	game.aspectratio = INHERIT;
	game.language = INHERIT;
	game.ocarina = INHERIT;
	game.vipatch = INHERIT;
	game.ios = INHERIT;
	game.autoios = INHERIT;
	game.parentalcontrol = PARENTAL_LVL_EVERYONE;
	game.patchcountrystrings = INHERIT;
	game.loadalternatedol = ALT_DOL_DEFAULT;
	game.alternatedolstart = 0;
	game.iosreloadblock = INHERIT;
	game.alternatedolname.clear();
	game.returnTo = ON;
	game.sneekVideoPatch = INHERIT;
	game.NandEmuMode = INHERIT;
	game.NandEmuPath.clear();
	game.Hooktype = INHERIT;
	game.WiirdDebugger = INHERIT;
	game.GameCubeMode = INHERIT;
	game.DMLVideo = INHERIT;
	game.DMLProgPatch = INHERIT;
	game.DMLNMM = INHERIT;
	game.DMLActivityLED = INHERIT;
	game.DMLPADHOOK = INHERIT;
	game.DMLNoDisc2 = INHERIT;
	game.DMLWidescreen = INHERIT;
	game.DMLScreenshot = INHERIT;
	game.DMLJPNPatch = INHERIT;
	game.DMLDebug = INHERIT;
	game.NINDeflicker = INHERIT;
	game.NINPal50Patch = INHERIT;
	game.NINWiiUWide = INHERIT;
	game.NINVideoScale = INHERIT;
	game.NINVideoOffset = INHERIT - 20;
	game.NINRemlimit = INHERIT;
	game.NINArcadeMode = INHERIT;
	game.NINCCRumble = INHERIT;
	game.NINSkipIPL = INHERIT;
	game.NINBBA = INHERIT;
	game.NINBBAProfile = INHERIT;
	game.NINMCEmulation = INHERIT;
	game.NINMCSize = INHERIT;
	game.NINUSBHID = INHERIT;
	game.NINMaxPads = INHERIT;
	game.NINNativeSI = INHERIT;
	game.NINOSReport = INHERIT;
	game.NINLED = INHERIT;
	game.NINLog = INHERIT;
	game.NINLoaderPath.clear();
	game.DEVOMCEmulation = INHERIT;
	game.DEVOWidescreen = INHERIT;
	game.DEVOActivityLED = INHERIT;
	game.DEVOFZeroAX = INHERIT;
	game.DEVOTimerFix = INHERIT;
	game.DEVODButtons = INHERIT;
	game.DEVOCropOverscan = INHERIT;
	game.DEVODiscDelay = INHERIT;
	game.PrivateServer = INHERIT;
	game.CustomAddress.clear();
	game.Locked = OFF;
}
