/****************************************************************************
 * Copyright (C) 2010
 * by Dimok
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any
 * damages arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any
 * purpose, including commercial applications, and to alter it and
 * redistribute it freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you
 * must not claim that you wrote the original software. If you use
 * this software in a product, an acknowledgment in the product
 * documentation would be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and
 * must not be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 * distribution.
 ***************************************************************************/
#include <ogcsys.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "CSettings.h"
#include "CGameSettings.h"
#include "FileOperations/fileops.h"
#include "svnrev.h"

#define VALID_CONFIG_REV	1031

CGameSettings GameSettings;

CGameSettings::CGameSettings()
{
	SetDefault(DefaultConfig);
}

CGameSettings::~CGameSettings()
{
}

GameCFG * CGameSettings::GetGameCFG(const char * id)
{
	if(!id)
	{
		DefaultConfig.id[0] = '\0';
		return &DefaultConfig;
	}

	const std::string key(id);
	if (GameMap.count(key)) {
		return GameMap[key].get();
	}

	memcpy(DefaultConfig.id, id, 6);

	return &DefaultConfig;
}

bool CGameSettings::AddGame(std::unique_ptr<GameCFG> NewGame)
{
	const std::string key(NewGame->id);
	GameMap[key] = std::move(NewGame);
	return true;
}

bool CGameSettings::RemoveAll()
{
	GameMap.clear();
	std::unordered_map<std::string, std::unique_ptr<GameCFG>>().swap(GameMap);

	return Save();
}

bool CGameSettings::Remove(const char * id)
{
	if(!id)
		return false;

	const std::string key(id);
	GameMap.erase(key);
	return true;
}

bool CGameSettings::Load(const char * path)
{
	char filepath[300];
	snprintf(filepath, sizeof(filepath), "%sGXGameSettings.cfg", path);

	ConfigPath = filepath;

	FILE *file = fopen(filepath, "r");
	if (!file) return false;

	if(!ValidVersion(file))
	{
		fclose(file);
		return false;
	}

	const int lineSize = 20*1024;

	char *line = new (std::nothrow) char[lineSize];
	if(!line) {
		fclose(file);
		return false;
	}

	while (fgets(line, lineSize, file))
	{
		if (line[0] == '#')
			continue;

		this->ParseLine(line);
	}

	delete [] line;

	fclose(file);

	return true;
}

bool CGameSettings::ValidVersion(FILE * file)
{
	if(!file) return false;

	char line[255];
	int revision = 0;

	while (fgets(line, sizeof(line), file))
	{
		const char * ptr = strcasestr(line, "USB Loader GX R");
		if(ptr)
		{
			ptr += strlen("USB Loader GX R");
			revision = atoi(ptr);
			break;
		}
	}

	rewind(file);

	return revision >= VALID_CONFIG_REV;
}

bool CGameSettings::Save()
{
	char filepath[300];
	strlcpy(filepath, ConfigPath.c_str(), sizeof(filepath));

	char * ptr = strrchr(filepath, '/');
	if(ptr)
		ptr[0] = 0;

	FILE * f = fopen(ConfigPath.c_str(), "w");
	if (!f) return false;

	fprintf(f, "# USB Loader GX R%s - Individual game settings file\n", GetRev());
	fprintf(f, "# note: this file is automatically generated\n");
	fprintf(f, "# Num Games: %d\n", GameMap.size());
	for (const auto& pair : GameMap)
	{
		GameCFG& game = *pair.second;

		fprintf(f, "game:%s = ", game.id);
		fprintf(f, "video:%d; ", game.video);
		fprintf(f, "videoPatchDol:%d; ", game.videoPatchDol);
		fprintf(f, "patchFix480p:%d; ", game.patchFix480p);
		fprintf(f, "deflicker:%d; ", game.deflicker);
		fprintf(f, "videowidth:%d; ", game.videoWidth);
		fprintf(f, "aspectratio:%d; ", game.aspectratio);
		fprintf(f, "language:%d; ", game.language);
		fprintf(f, "ocarina:%d; ", game.ocarina);
		fprintf(f, "vipatch:%d; ", game.vipatch);
		fprintf(f, "ios:%d; ", game.ios);
		fprintf(f, "autoios:%d; ", game.autoios);
		fprintf(f, "parentalcontrol:%d; ", game.parentalcontrol);
		fprintf(f, "iosreloadblock:%d; ", game.iosreloadblock);
		fprintf(f, "patchcountrystrings:%d; ", game.patchcountrystrings);
		fprintf(f, "loadalternatedol:%d; ", game.loadalternatedol);
		fprintf(f, "alternatedolstart:%d; ", (int)game.alternatedolstart);
		fprintf(f, "alternatedolname:%s; ", game.alternatedolname.c_str());
		fprintf(f, "returnTo:%d; ", game.returnTo);
		fprintf(f, "sneekVideoPatch:%d; ", game.sneekVideoPatch);
		fprintf(f, "NandEmuMode:%d; ", game.NandEmuMode);
		fprintf(f, "NandEmuPath:%s; ", game.NandEmuPath.c_str());
		fprintf(f, "Hooktype:%d; ", game.Hooktype);
		fprintf(f, "WiirdDebugger:%d; ", game.WiirdDebugger);
		fprintf(f, "GameCubeMode:%d; ", game.GameCubeMode);
		fprintf(f, "DMLVideo:%d; ", game.DMLVideo);
		fprintf(f, "DMLProgPatch:%d; ", game.DMLProgPatch);
		fprintf(f, "DMLNMM:%d; ", game.DMLNMM);
		fprintf(f, "DMLActivityLED:%d; ", game.DMLActivityLED);
		fprintf(f, "DMLPADHOOK:%d; ", game.DMLPADHOOK);
		fprintf(f, "DMLNoDisc2:%d; ", game.DMLNoDisc2);
		fprintf(f, "DMLWidescreen:%d; ", game.DMLWidescreen);
		fprintf(f, "DMLScreenshot:%d; ", game.DMLScreenshot);
		fprintf(f, "DMLJPNPatch:%d; ", game.DMLJPNPatch);
		fprintf(f, "DMLDebug:%d; ", game.DMLDebug);
		fprintf(f, "NINDeflicker:%d; ", game.NINDeflicker);
		fprintf(f, "NINPal50Patch:%d; ", game.NINPal50Patch);
		fprintf(f, "NINWiiUWide:%d; ", game.NINWiiUWide);
		fprintf(f, "NINVideoScale:%d; ", game.NINVideoScale);
		fprintf(f, "NINVideoOffset:%d; ", game.NINVideoOffset);
		fprintf(f, "NINRemlimit:%d; ", game.NINRemlimit);
		fprintf(f, "NINArcadeMode:%d; ", game.NINArcadeMode);
		fprintf(f, "NINCCRumble:%d; ", game.NINCCRumble);
		fprintf(f, "NINSkipIPL:%d; ", game.NINSkipIPL);
		fprintf(f, "NINBBA:%d; ", game.NINBBA);
		fprintf(f, "NINBBAProfile:%d; ", game.NINBBAProfile);
		fprintf(f, "NINMCEmulation:%d; ", game.NINMCEmulation);
		fprintf(f, "NINMCSize:%d; ", game.NINMCSize);
		fprintf(f, "NINUSBHID:%d; ", game.NINUSBHID);
		fprintf(f, "NINMaxPads:%d; ", game.NINMaxPads);
		fprintf(f, "NINNativeSI:%d; ", game.NINNativeSI);
		fprintf(f, "NINOSReport:%d; ", game.NINOSReport);
		fprintf(f, "NINLED:%d; ", game.NINLED);
		fprintf(f, "NINLog:%d; ", game.NINLog);
		fprintf(f, "NINLoaderPath:%s; ", game.NINLoaderPath.c_str());
		fprintf(f, "DEVOMCEmulation:%d; ", game.DEVOMCEmulation);
		fprintf(f, "DEVOWidescreen:%d; ", game.DEVOWidescreen);
		fprintf(f, "DEVOActivityLED:%d; ", game.DEVOActivityLED);
		fprintf(f, "DEVOFZeroAX:%d; ", game.DEVOFZeroAX);
		fprintf(f, "DEVOTimerFix:%d; ", game.DEVOTimerFix);
		fprintf(f, "DEVODButtons:%d; ", game.DEVODButtons);
		fprintf(f, "DEVOCropOverscan:%d; ", game.DEVOCropOverscan);
		fprintf(f, "DEVODiscDelay:%d; ", game.DEVODiscDelay);
		fprintf(f, "PrivateServer:%d; ", game.PrivateServer);
		fprintf(f, "CustomAddress:%s; ", game.CustomAddress.c_str());
		fprintf(f, "Locked:%d;\n", game.Locked);
	}
	fprintf(f, "# END\n");
	fclose(f);

	return true;
}

void CGameSettings::ApplySettings(
		GameCFG & game, std::unordered_map<std::string, std::unique_ptr<std::string>>& settings)
{
	std::unordered_map<std::string, std::unique_ptr<std::string>>::iterator it, end = settings.end();

	if ((it = settings.find("video")) != end) game.video = atoi(it->second->c_str());
	if ((it = settings.find("videoPatchDol")) != end) game.videoPatchDol = atoi(it->second->c_str());
	if ((it = settings.find("patchFix480p")) != end) game.patchFix480p = atoi(it->second->c_str());
	if ((it = settings.find("deflicker")) != end) game.deflicker = atoi(it->second->c_str());
	if ((it = settings.find("videowidth")) != end) game.videoWidth = atoi(it->second->c_str());
	if ((it = settings.find("aspectratio")) != end) game.aspectratio = atoi(it->second->c_str());
	if ((it = settings.find("language")) != end) game.language = atoi(it->second->c_str());
	if ((it = settings.find("ocarina")) != end) game.ocarina = atoi(it->second->c_str());
	if ((it = settings.find("vipatch")) != end) game.vipatch = atoi(it->second->c_str());
	if ((it = settings.find("ios")) != end) game.ios = atoi(it->second->c_str());
	if ((it = settings.find("autoios")) != end) game.autoios = atoi(it->second->c_str());
	if ((it = settings.find("parentalcontrol")) != end) game.parentalcontrol = atoi(it->second->c_str());
	if ((it = settings.find("iosreloadblock")) != end) game.iosreloadblock = atoi(it->second->c_str());
	if ((it = settings.find("loadalternatedol")) != end) game.loadalternatedol = atoi(it->second->c_str());
	if ((it = settings.find("alternatedolstart")) != end) game.alternatedolstart = atoi(it->second->c_str());
	if ((it = settings.find("patchcountrystrings")) != end) game.patchcountrystrings = atoi(it->second->c_str());
	if ((it = settings.find("alternatedolname")) != end) game.alternatedolname = it->second->c_str();
	if ((it = settings.find("returnTo")) != end) game.returnTo = atoi(it->second->c_str());
	if ((it = settings.find("sneekVideoPatch")) != end) game.sneekVideoPatch = atoi(it->second->c_str());
	if ((it = settings.find("NandEmuMode")) != end) game.NandEmuMode = atoi(it->second->c_str());
	if ((it = settings.find("NandEmuPath")) != end) game.NandEmuPath = it->second->c_str();
	if ((it = settings.find("Hooktype")) != end) game.Hooktype = atoi(it->second->c_str());
	if ((it = settings.find("WiirdDebugger")) != end) game.WiirdDebugger = atoi(it->second->c_str());
	if ((it = settings.find("Locked")) != end) game.Locked = atoi(it->second->c_str());
	if ((it = settings.find("GameCubeMode")) != end) game.GameCubeMode = atoi(it->second->c_str());
	if ((it = settings.find("DMLVideo")) != end) game.DMLVideo = atoi(it->second->c_str());
	if ((it = settings.find("DMLProgPatch")) != end) game.DMLProgPatch = atoi(it->second->c_str());
	if ((it = settings.find("DMLNMM")) != end) game.DMLNMM = atoi(it->second->c_str());
	if ((it = settings.find("DMLActivityLED")) != end) game.DMLActivityLED = atoi(it->second->c_str());
	if ((it = settings.find("DMLPADHOOK")) != end) game.DMLPADHOOK = atoi(it->second->c_str());
	if ((it = settings.find("DMLNoDisc2")) != end) game.DMLNoDisc2 = atoi(it->second->c_str());
	if ((it = settings.find("DMLWidescreen")) != end) game.DMLWidescreen = atoi(it->second->c_str());
	if ((it = settings.find("DMLScreenshot")) != end) game.DMLScreenshot = atoi(it->second->c_str());
	if ((it = settings.find("DMLJPNPatch")) != end) game.DMLJPNPatch = atoi(it->second->c_str());
	if ((it = settings.find("DMLDebug")) != end) game.DMLDebug = atoi(it->second->c_str());
	if ((it = settings.find("NINDeflicker")) != end) game.NINDeflicker = atoi(it->second->c_str());
	if ((it = settings.find("NINPal50Patch")) != end) game.NINPal50Patch = atoi(it->second->c_str());
	if ((it = settings.find("NINWiiUWide")) != end) game.NINWiiUWide = atoi(it->second->c_str());
	if ((it = settings.find("NINVideoScale")) != end) game.NINVideoScale = atoi(it->second->c_str());
	if ((it = settings.find("NINVideoOffset")) != end) game.NINVideoOffset = atoi(it->second->c_str());
	if ((it = settings.find("NINRemlimit")) != end) game.NINRemlimit = atoi(it->second->c_str());
	if ((it = settings.find("NINArcadeMode")) != end) game.NINArcadeMode = atoi(it->second->c_str());
	if ((it = settings.find("NINCCRumble")) != end) game.NINCCRumble = atoi(it->second->c_str());
	if ((it = settings.find("NINSkipIPL")) != end) game.NINSkipIPL = atoi(it->second->c_str());
	if ((it = settings.find("NINBBA")) != end) game.NINBBA = atoi(it->second->c_str());
	if ((it = settings.find("NINBBAProfile")) != end) game.NINBBAProfile = atoi(it->second->c_str());
	if ((it = settings.find("NINMCEmulation")) != end) game.NINMCEmulation = atoi(it->second->c_str());
	if ((it = settings.find("NINMCSize")) != end) game.NINMCSize = atoi(it->second->c_str());
	if ((it = settings.find("NINUSBHID")) != end) game.NINUSBHID = atoi(it->second->c_str());
	if ((it = settings.find("NINMaxPads")) != end) game.NINMaxPads = atoi(it->second->c_str());
	if ((it = settings.find("NINNativeSI")) != end) game.NINNativeSI = atoi(it->second->c_str());
	if ((it = settings.find("NINOSReport")) != end) game.NINOSReport = atoi(it->second->c_str());
	if ((it = settings.find("NINLED")) != end) game.NINLED = atoi(it->second->c_str());
	if ((it = settings.find("NINLog")) != end) game.NINLog = atoi(it->second->c_str());
	if ((it = settings.find("NINLoaderPath")) != end) game.NINLoaderPath = it->second->c_str();
	if ((it = settings.find("DEVOMCEmulation")) != end) game.DEVOMCEmulation = atoi(it->second->c_str());
	if ((it = settings.find("DEVOWidescreen")) != end) game.DEVOWidescreen = atoi(it->second->c_str());
	if ((it = settings.find("DEVOActivityLED")) != end) game.DEVOActivityLED = atoi(it->second->c_str());
	if ((it = settings.find("DEVOFZeroAX")) != end) game.DEVOFZeroAX = atoi(it->second->c_str());
	if ((it = settings.find("DEVOTimerFix")) != end) game.DEVOTimerFix = atoi(it->second->c_str());
	if ((it = settings.find("DEVODButtons")) != end) game.DEVODButtons = atoi(it->second->c_str());
	if ((it = settings.find("DEVOCropOverscan")) != end) game.DEVOCropOverscan = atoi(it->second->c_str());
	if ((it = settings.find("DEVODiscDelay")) != end) game.DEVODiscDelay = atoi(it->second->c_str());
	if ((it = settings.find("PrivateServer")) != end) game.PrivateServer = atoi(it->second->c_str());

	if ((it = settings.find("CustomAddress")) != end)
	{
		if(it->second->length() > 3)
			game.CustomAddress = it->second->c_str();
	}
}

bool CGameSettings::ReadGameID(const char * src, char * GameID, int size)
{
	if(strncasecmp(src, "game:", 5) != 0)
		return false;

	char * ptr = strchr(src, ':');
	if(!ptr)
		return false;

	ptr++;

	int i = 0;

	for(i = 0; i < size; i++, ptr++)
	{
		if(*ptr == ' ' || *ptr == '\0')
			break;

		GameID[i] = *ptr;
	}

	GameID[i] = 0;

	return true;
}

void CGameSettings::ParseLine(char *line)
{
	char GameID[8];

	if(!ReadGameID(line, GameID, 6))
		return;

	if(strlen(GameID) != 6 && strlen(GameID) != 4)
		return;

	std::unique_ptr<GameCFG> NewCFG = std::make_unique<GameCFG>();
	SetDefault(*NewCFG);

	strcpy(NewCFG->id, GameID);

	char * LinePtr = strchr(line, '=');

	std::unordered_map<std::string, std::unique_ptr<std::string>> parsed_settings;

	while(LinePtr != NULL)
	{
		LinePtr++;

		char * eq = strchr(LinePtr, ':');

		if (!eq) break;

		std::string name;
		std::unique_ptr<std::string> value = std::make_unique<std::string>();

		this->TrimLine(name, LinePtr, ':');
		this->TrimLine(*value, eq + 1, ';');

		parsed_settings[name] = std::move(value);

		LinePtr = strchr(LinePtr, ';');
	}

	ApplySettings(*NewCFG, parsed_settings);
	AddGame(std::move(NewCFG));
}

void CGameSettings::TrimLine(std::string &dest, const char *src, char stopChar)
{
	if(!src)
		return;

	while (*src == ' ')
		src++;

	while(*src != 0)
	{
		if(*src == stopChar || *src == '\n' || *src == '\r')
			break;

		dest.push_back(*src);
		src++;
	}
}

int CGameSettings::GetPartenalPEGI(int parental)
{
	switch(parental)
	{
		case 1: return 7;
		case 2: return 12;
		case 3: return 16;
		case 4: return 18;
		default: return -1;
	}
}

void CGameSettings::SetDefault(GameCFG &game)
{
	memset(game.id, 0, sizeof(game.id));
	game.video = INHERIT;
	game.videoPatchDol = INHERIT;
	game.patchFix480p = INHERIT;
	game.deflicker = INHERIT;
	game.videoWidth = INHERIT;
	game.aspectratio = INHERIT;
	game.language = INHERIT;
	game.ocarina = INHERIT;
	game.vipatch = INHERIT;
	game.ios = INHERIT;
	game.autoios = INHERIT;
	game.parentalcontrol = PARENTAL_LVL_EVERYONE;
	game.patchcountrystrings = INHERIT;
	game.loadalternatedol = ALT_DOL_DEFAULT;
	game.alternatedolstart = 0;
	game.iosreloadblock = INHERIT;
	game.alternatedolname.clear();
	game.returnTo = ON;
	game.sneekVideoPatch = INHERIT;
	game.NandEmuMode = INHERIT;
	game.NandEmuPath.clear();
	game.Hooktype = INHERIT;
	game.WiirdDebugger = INHERIT;
	game.GameCubeMode = INHERIT;
	game.DMLVideo = INHERIT;
	game.DMLProgPatch = INHERIT;
	game.DMLNMM = INHERIT;
	game.DMLActivityLED = INHERIT;
	game.DMLPADHOOK = INHERIT;
	game.DMLNoDisc2 = INHERIT;
	game.DMLWidescreen = INHERIT;
	game.DMLScreenshot = INHERIT;
	game.DMLJPNPatch = INHERIT;
	game.DMLDebug = INHERIT;
	game.NINDeflicker = INHERIT;
	game.NINPal50Patch = INHERIT;
	game.NINWiiUWide = INHERIT;
	game.NINVideoScale = INHERIT;
	game.NINVideoOffset = INHERIT - 20;
	game.NINRemlimit = INHERIT;
	game.NINArcadeMode = INHERIT;
	game.NINCCRumble = INHERIT;
	game.NINSkipIPL = INHERIT;
	game.NINBBA = INHERIT;
	game.NINBBAProfile = INHERIT;
	game.NINMCEmulation = INHERIT;
	game.NINMCSize = INHERIT;
	game.NINUSBHID = INHERIT;
	game.NINMaxPads = INHERIT;
	game.NINNativeSI = INHERIT;
	game.NINOSReport = INHERIT;
	game.NINLED = INHERIT;
	game.NINLog = INHERIT;
	game.NINLoaderPath.clear();
	game.DEVOMCEmulation = INHERIT;
	game.DEVOWidescreen = INHERIT;
	game.DEVOActivityLED = INHERIT;
	game.DEVOFZeroAX = INHERIT;
	game.DEVOTimerFix = INHERIT;
	game.DEVODButtons = INHERIT;
	game.DEVOCropOverscan = INHERIT;
	game.DEVODiscDelay = INHERIT;
	game.PrivateServer = INHERIT;
	game.CustomAddress.clear();
	game.Locked = OFF;
}
